### ISSUE TITLE
Upload .svg files for logo

### ISSUE THREAD

**Issue by camilamaia** [scanapi/design#2]
Upload .svg files for:

- icon-dark.png
- logo-white-on-black.png

**Comment by barbosa** [comment]
@camilamaia can you list the ones you'd like to have in an SVG format? Just so I open Sketch and select them to be exported correctly? Thank you!

**Comment by camilamaia** [comment]
@barbosa sure thing! I updated the PR description with the info. I believe with these two we can easily reach the others by just changing the colors.

Thanks!
